# Generated by Django 3.2.7 on 2021-09-04 21:27

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name="Унікальне ім'я")),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name="Унікальне ім'я")),
                ('description', models.TextField(verbose_name='Опис')),
                ('status', models.CharField(choices=[('team-set', 'Набір учасників'), ('in-development', 'У розробці'), ('paused', 'Призупинено'), ('canceled', 'Відмінено'), ('finished', 'Завершено'), ('testing', 'Тестується'), ('promoted', 'У процесі просування')], default='team-set', max_length=32, verbose_name='Статус')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата створення')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Бюджет проекту')),
                ('categories', models.ManyToManyField(related_name='related_categories', to='mainapp.Category', verbose_name='Категорії, до яких відноситься проект')),
                ('files', models.ManyToManyField(to='mainapp.File', verbose_name='Вкладені файли')),
                ('followers', models.ManyToManyField(related_name='related_followers', to=settings.AUTH_USER_MODEL, verbose_name='Підписники')),
                ('members', models.ManyToManyField(related_name='related_members', to=settings.AUTH_USER_MODEL, verbose_name='Учасники')),
            ],
        ),
    ]
