# Generated by Django 3.2.7 on 2021-09-25 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name="Унікальне ім'я")),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name="Ім'я користувача")),
                ('user_ip', models.CharField(max_length=255, verbose_name='ІР користувача')),
                ('text', models.TextField(verbose_name='Коментар')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата та час створення')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name="Ім'я користувача")),
                ('user_ip', models.CharField(max_length=255, verbose_name='ІР користувача')),
                ('text', models.TextField(verbose_name='Відгук')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата та час створення')),
                ('visible', models.BooleanField(default=False, verbose_name='Відобразити на сайті')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='StartupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(blank=True, max_length=64, verbose_name='По-батькові')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Номер телефону')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('date_of_accession', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Зображення')),
                ('role', models.CharField(max_length=255, verbose_name='Роль у стартапі')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name="Унікальне ім'я")),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Зображення')),
                ('short_description', models.TextField(null=True, verbose_name='Короткий опис')),
                ('description', models.TextField(verbose_name='Опис')),
                ('status', models.CharField(choices=[('team-set', 'Набір учасників'), ('in-development', 'У розробці'), ('paused', 'Призупинено'), ('canceled', 'Відмінено'), ('finished', 'Завершено'), ('testing', 'Тестується'), ('promoted', 'У процесі просування')], default='team-set', max_length=32, verbose_name='Статус')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата та час створення')),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Бюджет проекту')),
                ('categories', models.ManyToManyField(related_name='related_categories', to='mainapp.Category', verbose_name='Категорії, до яких відноситься проект')),
                ('comments', models.ManyToManyField(blank=True, related_name='related_comments', to='mainapp.Comment', verbose_name='Коментарі')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('files', models.ManyToManyField(blank=True, to='mainapp.File', verbose_name='Вкладені файли')),
                ('followers', models.ManyToManyField(blank=True, related_name='related_followers', to=settings.AUTH_USER_MODEL, verbose_name='Підписники')),
                ('members', models.ManyToManyField(blank=True, related_name='related_members', to='mainapp.StartupMember', verbose_name='Учасники')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(upload_to='', verbose_name='Зображення')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата та час створення')),
                ('attached_files', models.ManyToManyField(blank=True, related_name='related_post_attached_files', to='mainapp.File', verbose_name='Вкладені файли')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='attached_files',
            field=models.ManyToManyField(blank=True, related_name='related_comment_attached_files', to='mainapp.File', verbose_name='Вкладені файли'),
        ),
        migrations.AddField(
            model_name='comment',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='_mainapp_comment_children_+', to='mainapp.Comment', verbose_name='Відповіді до цього коментаря'),
        ),
    ]
