# Generated by Django 3.2.7 on 2021-09-10 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name="Ім'я користувача")),
                ('user_ip', models.CharField(max_length=255, verbose_name='ІР користувача')),
                ('text', models.TextField(verbose_name='Відгук')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата та час створення')),
                ('visible', models.BooleanField(default=False, verbose_name='Відобразити на сайті')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(upload_to='', verbose_name='Зображення')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата та час створення')),
                ('attached_files', models.ManyToManyField(related_name='related_attached_files', to='mainapp.File', verbose_name='Вкладені файли')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
    ]
