# Generated by Django 3.2.7 on 2021-09-11 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0002_feedback_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Автор'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='startup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='post',
            name='attached_files',
            field=models.ManyToManyField(related_name='related_post_attached_files', to='mainapp.File', verbose_name='Вкладені файли'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Бюджет проекту'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата та час створення'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name="Ім'я користувача")),
                ('user_ip', models.CharField(max_length=255, verbose_name='ІР користувача')),
                ('text', models.TextField(verbose_name='Коментар')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата та час створення')),
                ('attached_files', models.ManyToManyField(related_name='related_comment_attached_files', to='mainapp.File', verbose_name='Вкладені файли')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.comment', verbose_name='Відповідь до коментаря')),
            ],
        ),
        migrations.AddField(
            model_name='startup',
            name='comments',
            field=models.ManyToManyField(related_name='related_comments', to='mainapp.Comment', verbose_name='Коментарі'),
        ),
    ]
