# Generated by Django 3.2.7 on 2021-09-11 17:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0003_auto_20210911_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='attached_files',
            field=models.ManyToManyField(blank=True, related_name='related_comment_attached_files', to='mainapp.File', verbose_name='Вкладені файли'),
        ),
        migrations.AlterField(
            model_name='post',
            name='attached_files',
            field=models.ManyToManyField(blank=True, related_name='related_post_attached_files', to='mainapp.File', verbose_name='Вкладені файли'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='files',
            field=models.ManyToManyField(blank=True, to='mainapp.File', verbose_name='Вкладені файли'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='related_followers', to=settings.AUTH_USER_MODEL, verbose_name='Підписники'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='related_members', to=settings.AUTH_USER_MODEL, verbose_name='Учасники'),
        ),
    ]
