# Generated by Django 3.2.7 on 2021-09-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210911_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='related_comments', to='mainapp.Comment', verbose_name='Коментарі'),
        ),
    ]
